source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'BonjourWeb_Example', :exclusive => true do
  pod "BonjourWeb", :path => "../"
end

target 'BonjourWeb_Tests', :exclusive => true do
  pod "BonjourWeb", :path => "../"

  pod 'Specta'
  pod 'Expecta'
end
